import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";




// Import Google Font IBM Plex Sans
const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// Import Google Font Bebas Neue
const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--bebas-neue",
  display: "swap",
});

export const metadata: Metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
}: {
  children: React.ReactNode;
}) => {

  const session = await auth();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body
          className={`${ibmPlexSans.className} ${bebasNeue.variable} antialiased `}
        >
          {children}
          <Toaster />
        </body>
      </SessionProvider>

    </html>
  );
};

export default RootLayout;
